// Run with Node 22.13+ (node:sqlite) after npm install. No network or real clinic data.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite'),ts=require('typescript');
const root=path.resolve(__dirname,'..'),noop=()=>{},log={info:noop,warn:noop,error:noop};
let failQueue=false;
class SQLiteAdapter {
 constructor(file){this.db=new DatabaseSync(file);this.depth=0;}
 pragma(sql){this.db.exec('PRAGMA '+sql)} exec(sql){this.db.exec(sql)} close(){this.db.close()}
 prepare(sql){const st=this.db.prepare(sql);return {all:(...a)=>st.all(...a),get:(...a)=>st.get(...a),run:(...a)=>{if(failQueue&&/INSERT INTO mutation_queue/.test(sql))throw Error('simulated disk failure');return st.run(...a)}}}
 transaction(fn){return (...args)=>{const n=++this.depth,key='t'+n;this.db.exec('SAVEPOINT '+key);try{const value=fn(...args);this.db.exec('RELEASE '+key);return value}catch(e){this.db.exec('ROLLBACK TO '+key);this.db.exec('RELEASE '+key);throw e}finally{--this.depth}}}
}
const moduleStore={exports:{}};
vm.runInNewContext(fs.readFileSync(root+'/sqlite-store.cjs','utf8'),{module:moduleStore,require:n=>n==='better-sqlite3'?SQLiteAdapter:n==='./logger.cjs'?{logInfo:noop,logError:noop}:require(n),console});
const testDir=fs.mkdtempSync(path.join(require('os').tmpdir(),'balaji-offline-test-'));
const store=moduleStore.exports;store.init(testDir);
const storage=new Map([["bocc_selected_branch","00000000-0000-4000-8000-000000000010"]]);const localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};
const bridge={};
for(const name of ['cacheMergeServer','cacheGetAll','cacheGetRow','cacheSetRows','cacheReplaceTable','cacheUpsertRow','cacheDeleteRow','cacheReplaceRowKey','queueGetAll','queueRemove','queueUpdate','metaSet','commitBatch','commitMutation','snapshot','restoreSnapshot','adjustStock'])
 bridge[name]=async(...args)=>{try{return {success:true,data:structuredClone(store[name](...args))}}catch(e){return {success:false,error:e.message}}};
bridge.queueAdd=async m=>{try{return {success:true,id:store.queueAdd(m)}}catch(e){return {success:false,id:-1,error:e.message}}};
bridge.metaGet=async key=>({success:true,value:store.metaGet(key)});
const windowMock={electron:{offline:bridge},addEventListener:noop};
function load(file,names,deps={}){
 let source=fs.readFileSync(root+'/'+file,'utf8').replace(/^import[\s\S]*?from\s+["'][^"']+["'];?/gm,'').replaceAll('import.meta.env','({})');
 source=ts.transpile(source.replace(/\bexport\s+/g,''),{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS});
 const ctx={normalizeBill:require("./audit-fixtures.cjs").normalizeBill,ensureCloudSession:async()=>true,exports:{},console,window:windowMock,localStorage,navigator:{onLine:false},cLog:log,crypto:require('crypto').webcrypto,Blob,atob,setTimeout,setInterval,clearTimeout,clearInterval,...deps};
 if (ctx.supabase) ctx.supabase = require("./audit-fixtures.cjs").queryMock(ctx.supabase);
 vm.createContext(ctx);vm.runInContext(source+'\n;globalThis.api={'+names.join(',')+'};',ctx);return ctx.api;
}
const db=load('src/lib/offlineDb.ts',['cacheUpsertRowFromServer','cacheGetAll','cacheGetRow','cacheUpsertRow','cacheReplaceTable','cacheSetRows','cacheDeleteRow','cacheReplaceRowKey','queueAdd','queueGetAll','queueUpdate','queueRemove','queueRemapRowId','commitBatch','commitMutation','tempId','getLocalSnapshot','atomicStockAdjustment','MAX_SYNC_RETRIES']);
const payment=load('src/lib/paymentLedger.ts',['paymentHistory','withPaymentHistory','collectionRows']);
const offline=load('src/lib/offlineQuery.ts',['offlineInsert','offlineUpdate','offlineDelete'],{...db,...payment,isOnline:async()=>false,runSync:noop});

const read=f=>fs.readFileSync(root+'/'+f,'utf8').replace(/\r\n/g,'\n');
function expression(file,name){const sf=ts.createSourceFile(file,read(file),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let out;function walk(n){if(ts.isVariableDeclaration(n)&&n.name.getText(sf)===name&&n.initializer)out=n.initializer.getText(sf);ts.forEachChild(n,walk)}walk(sf);assert.ok(out,name);return out}
function ev(code,deps={}){const c={console,Date,URL,...deps};vm.runInNewContext(ts.transpile('globalThis.out=('+code+');',{target:ts.ScriptTarget.ES2022}),c);return c.out}
const uid=()=>require('crypto').randomUUID(),reset=()=>{for(const m of store.queueGetAll())store.queueRemove(m.id)};
const passed=[];const pass=(id)=>{passed.push(id);console.log('PASS',id)};
(async()=>{
 // B01 actual reset handler cannot remove a file even if IPC is called directly.
 let handler;const main=read('main.js');let a=main.indexOf("ipcMain.handle('app:nuclearIndexedDBReset'");let b=main.indexOf('\n}));',a)+5;
 vm.runInNewContext(main.slice(a,b),{ipcMain:{handle:(_,fn)=>handler=fn}});assert.equal((await handler()).success,false);pass('B01 reset safely refuses');
 assert.ok(!read('src/pages/Ortho.tsx').includes('AUTO_DELETE_KEY'));pass('B02 automatic X-ray deletion removed');
 let state=[],i=0,effects=[];const hook=read('src/hooks/useIsAdmin.ts').replace(/^import .*;\n/gm,'').replace('export function','function');vm.runInNewContext(ts.transpile(hook+';useIsAdmin();'),{window:{electron:{checkAuth:async()=>({valid:true,principal:{role:'admin'}})}},useState:v=>{const k=i++;state[k]=v;return[v,x=>state[k]=x]},useEffect:f=>effects.push(f),setInterval:noop,clearInterval:noop});effects[0]();await new Promise(setImmediate);assert.equal(state[0],true);pass('B03 local administrator recognized without cloud');
 const badge=read('src/components/SyncStatusBadge.tsx');a=badge.indexOf('const offSync  = ');b=badge.indexOf('\n\n',a);let success=false,error=null;vm.runInNewContext(ts.transpile(badge.slice(a,b)),{onSyncStatus:fn=>fn({syncing:false,pending:0,lastError:'Cloud pending'}),setSyncing:noop,setPending:noop,setSyncError:v=>error=v,setJustSynced:v=>success=v,setTimeout:noop});assert.equal(success,false);assert.equal(error,'Cloud pending');pass('B04 cloud error never claims synced');
 const p=await offline.offlineInsert('patients',{name:'cascade'});const bill=await offline.offlineInsert('billing',{patient_id:p.id,amount:100,amount_paid:0});await offline.offlineDelete('patients',p.id);assert.equal(store.cacheGetRow('billing',bill.id),undefined);assert.equal(store.queueGetAll().some(m=>m.table==='billing'),false);pass('B05 local cascade cancels dependent queue');reset();
 const tally=ev(expression('src/pages/Billing.tsx','cashTally'),{filteredBills:[{amount:1000,discount:200,amount_paid:800}]});assert.equal(tally.pending,0);pass('B06 net due after discount');
 let selected;const profile=ev(expression('src/pages/PatientProfile.tsx','fetchData'),{id:'patient-test',setLoading:noop,setPatient:p=>selected=p,setBills:noop,setPhysio:noop,setXrays:noop,setMedicines:noop,cacheGetAll:async t=>t==='patients'?[{id:'patient-test',name:'local'}]:[],supabase:{from:()=>{throw Error('Must not wait for cloud')}},cLog:log,toast:noop});await profile();assert.equal(selected.name,'local');pass('B07 local patient profile survives cloud outage');
 store.cacheUpsertRow('patients',{id:'merge-test',branch_id:'a',age:40},'id');store.cacheMergeServer('patients',{id:'merge-test',name:'updated'});assert.equal(store.cacheGetRow('patients','merge-test').age,40);pass('B08 partial merge preserves fields');
 const inv=load('src/lib/invoiceNumber.ts',['invoiceNumber']);assert.equal(inv.invoiceNumber('local_ab123'),inv.invoiceNumber('ab123'));assert.notEqual(inv.invoiceNumber('local_ab123'),inv.invoiceNumber('local_ab456'));pass('B09 stable distinct invoice numbers');
 store.cacheUpsertRow('medicine_entries',{id:'entry-old',total_amount:10},'id');const before=JSON.stringify(store.snapshot());assert.throws(()=>store.commitBatch([{mutation:{table:'medicine_entries',op:'delete',rowId:'entry-old'},row:null},{mutation:{table:'medicine_entries',op:'update',rowId:'missing'},row:{total_amount:20}}]),/not available/);assert.equal(JSON.stringify(store.snapshot()),before);pass('B10 batch failure restores old medicine entry and queue');
 for(const f of ['src/pages/MedicineMaster.tsx','src/pages/PatientMedicine.tsx'])assert.ok(!read(f).includes('id: "med1"'));pass('B11 no fake medicines');
 assert.ok(!read('src/pages/MedicineCommission.tsx').includes('ADMIN_PASS'));assert.ok(!read('src/pages/MedicineCommission.tsx').includes('sessionStorage'));pass('B12 shared frontend password removed');
 assert.ok(!read('src/pages/PlasterSync.tsx').includes('.from("fracture_cases"'));assert.ok(read('src/pages/Reports.tsx').includes('uploadClinicalFile'));assert.ok(read('src/pages/MedicineCommission.tsx').includes("cacheGetAll('medicine_entries')"));pass('B13 offline workflows use durable local storage');
 assert.ok(read('src/App.tsx').includes('setInterval(() => { if (shouldShowLock())'));pass('B14 foreground lock timer installed');
 const scheduler=read('src/lib/backup.ts').split('export function startAutoBackupScheduler()')[1];assert.ok(!scheduler.includes('if (!online) return'));pass('B15 backups no longer skipped offline');
 const request={id:uid(),patient_name:'Existing',mobile:'9999999999',preferred_date:'2026-10-07',preferred_time:null,reason:'Test'};const cached={id:uid(),name:'Existing',mobile:'9999999999',branch_id:'a'};let group;const confirm=ev(expression('src/pages/BookingRequests.tsx','confirmAndCreateAppointment'),{processing:{current:new Set()},cacheGetAll:async t=>t==='patients'?[cached]:t==='booking_requests'?[{...request,status:'Pending'}]:[],localStorage,commitBatch:async items=>group=items,runSync:async()=>{},queryClient:{invalidateQueries:noop},toast:noop});await confirm(request);assert.equal(group.some(i=>i.mutation.table==='patients'),false);assert.equal(group.find(i=>i.mutation.table==='appointments').row.patient_id,cached.id);pass('B16 cached patient reused and booking saved as one transaction');
 let copied=false;const copy=ev(expression('src/pages/BookingRequests.tsx','copyBookingLink').replace('import.meta.env.VITE_PUBLIC_BOOKING_URL','undefined'),{window:{location:new URL('file:///C:/app/index.html')},navigator:{clipboard:{writeText:async()=>copied=true}},toast:noop});await copy();assert.equal(copied,false);pass('B17 desktop does not publish an invalid booking URL');
 let upload;const file=load('src/hooks/useOrtho.ts',['uploadClinicalFile'],{businessDate:()=> '2026-10-07',commitMutation:async(m,row)=>{upload={m,row};throw Error('stop after inspecting transaction')},FileReader:class{readAsDataURL(){this.result='data:image/png;base64,YQ==';this.onload()}}});await assert.rejects(()=>file.uploadClinicalFile('fracture_xrays','p',{type:'image/png',name:'x.png'},'c'),/inspecting/);assert.equal(upload.m.op,'xray_upload');assert.equal(upload.row._pendingSync,true);assert.equal(upload.row.file_url,'data:image/png;base64,YQ==');pass('B18 upload bytes and visible preview committed together');
 const ledger=require('./audit-fixtures.cjs');assert.equal(ledger.normalizeBill({amount:100,amount_paid:0,discount:null}).discount,0);const normalized=await offline.offlineInsert('billing',{amount:100,amount_paid:0,discount:null});assert.equal(normalized.discount,0);pass('C01 null discount repaired before local commit');reset();
 const total=ev(expression('src/pages/Billing.tsx','totalAmount'),{services:[{name:'X-Ray',amount:'100'},{name:'',amount:'900'}]});assert.equal(total,100);pass('C02 incomplete service excluded from total (form refuses save)');
 await assert.rejects(()=>offline.offlineInsert('billing',{amount:-100,amount_paid:0}),/non-negative/);await assert.rejects(()=>offline.offlineInsert('billing',{amount:100,amount_paid:-10}),/non-negative/);pass('C03 negative values rejected before durable save');
 let navigated=false,toasts=[];const register=ev(expression('src/pages/OPD.tsx','handleRegister'),{regForm:{name:'Edited',mobile:'9999999999',age:'40'},mobileSearchStatus:'found',existingPatient:{id:'old'},registering:{current:false},mobileRequest:{current:0},offlineUpdate:async()=>{throw Error('disk full')},cLog:log,toast:v=>toasts.push(v),setTimeout:f=>f(),navigate:()=>navigated=true,setRegForm:noop,setExistingPatient:noop,setMobileSearchStatus:noop});await register({preventDefault:noop});assert.equal(navigated,false);assert.ok(toasts.some(t=>t.description==='disk full'));pass('C04 save failure never claims success or navigates');
 let form={},current,status,reads=0;const pending=[];const lookup=ev(expression('src/pages/OPD.tsx','handleMobileChange'),{mobileRequest:{current:0},registering:{current:false},setRegForm:v=>form=typeof v==='function'?v(form):v,setExistingPatient:v=>current=v,setMobileSearchStatus:v=>status=v,cacheGetAll:()=>{reads++;return new Promise(resolve=>pending.push(resolve))},isOnline:async()=>false,toast:noop});const one=lookup('9999999991'),two=lookup('9999999992');pending[1]([{id:'second',mobile:'9999999992',name:'Second'}]);await two;pending[0]([{id:'first',mobile:'9999999991',name:'First'}]);await one;assert.equal(current.id,'second');assert.equal(form.mobile,'9999999992');pass('C05 obsolete lookup cannot change patient');assert.equal(reads,2);assert.equal(status,'found');pass('C08 local lookup completes without cloud wait');
 reset();const parent=await offline.offlineInsert('patients',{name:'Parent'});const child=await offline.offlineInsert('billing',{patient_id:parent.id,amount:100,amount_paid:0});store.cacheReplaceRowKey('patients',parent.id,{id:parent.id.slice(6),name:'Parent'},'id');assert.equal(store.cacheGetRow('billing',child.id).patient_id,parent.id.slice(6));assert.equal(store.queueGetAll().find(m=>m.table==='billing').payload.patient_id,parent.id.slice(6));assert.equal(store.cacheGetRow('patients',parent.id).id,parent.id.slice(6));pass('C06 remap preserves child relationships and stale UI aliases');reset();
 let remote,lose=true;const cloud={from:()=>({upsert:(p,opts)=>({select:()=>({maybeSingle:async()=>{assert.equal(opts.ignoreDuplicates,true);if(remote)return{data:null,error:null};remote={...p};if(lose){lose=false;return{error:Error('reply lost')}}return{data:remote}}})}),select:()=>({eq:()=>({single:async()=>({data:remote})})})})};const replay=load('src/lib/offlineSync.ts',['applyMutation'],{...db,supabase:cloud});const id='local_'+uid();store.cacheUpsertRow('patients',{id,name:'original'},'id');const mutation={id:9999,table:'patients',op:'insert',tempId:id,payload:{id,name:'original'}};await assert.rejects(()=>replay.applyMutation(mutation),/reply lost/);remote.name='Newer edit';await replay.applyMutation(mutation);assert.equal(remote.name,'Newer edit');pass('C07 retry acknowledges existing insert without overwriting newer edit');
 let updateSent;
 const updating=load('src/lib/offlineSync.ts',['applyMutation'],{...db,supabase:{from:()=>({update:p=>{updateSent=p;return{eq:()=>({select:()=>({single:async()=>({data:{id:'canonical',...p}})})})}}})}});
 await updating.applyMutation({id:12345,table:'medicine_entries',op:'update',rowId:'canonical',payload:{id:'local_canonical',total_amount:10}});
 assert.equal(updateSent.id,undefined);pass('C06 queued updates cannot change primary keys back to temporary IDs');
 const ac=require(root+'/access-control.cjs');ac.setPrincipal({role:'staff',userId:'staff',pages:['/opd'],branchIds:null,expiresAt:Date.now()+10000});const snap=JSON.stringify(store.snapshot());assert.throws(()=>store.authorizedBatch([{mutation:{table:'patients',op:'insert',tempId:'test-safe'},row:{id:'test-safe',name:'test'}},{mutation:{table:'billing',op:'insert',tempId:'forbidden'},row:{id:'forbidden'}}],item=>ac.authorize('offline:commitMutation',[item],store),'staff'),/Access denied/);assert.equal(JSON.stringify(store.snapshot()),snap);pass('Security: later denied batch member rolls back earlier authorized write');
 console.log('PASS',passed.length,'checks covering B01–B18 and C01–C08');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>{store.close();fs.rmSync(testDir,{recursive:true,force:true})});
